import { Mongo } from 'meteor/mongo';

export const Characters = new Mongo.Collection('characters');

Meteor.methods({
	'character.insert'     : character => Characters.insert({ ...defaultCharacter, ...character }),
	'character.deactivate' :    _id    => Characters.update({ _id }, { $set : { inactive : true } }),
  'character.remove'     :    _id    => Characters.remove({ _id }),
	'character.update'     : (_id, character) => Characters.update({ _id }, character),
});

const defaultCharacter = {
  userId          : null,
  campaignId      : null,
  inactive       : false,
  firstName       : '',
  middleName      : '',
  lastName        : '',
  title           : '',
  characterType   : '',
  race            : '',
  sex             : '',
  heightM         : 0,
  heightCm        : 0,
  weight          : 0,
  birthday        : '',
  age             : 0,
  description     : '',
  bronze          : 0,
  silver          : 0,
  gold            : 0,
  inventory       : '',
  diety           : '',
  alignment       : '',
  hp              : 0,
  damage          : 0,
  hpBonus         : 0,
  str             : 0,
  int             : 0,
  wis             : 0,
  con             : 0,
  dex             : 0,
  cha             : 0,
  strBonus        : 0,
  intBonus        : 0,
  wisBonus        : 0,
  conBonus        : 0,
  dexBonus        : 0,
  chaBonus        : 0,
  movement        : 2,
  movementBonus   : 0,
  hitRoll         : 0,
  hitRollBonus    : 0,
  ac              : 0,
  acBonus         : 0,
  evade           : 0,
  block           : 0,
  evadeBonus      : 0,
  level0          : 0,
  level1          : 0,
  level2          : 0,
  level3          : 0,
  level4          : 0,
  level5          : 0,
  level6          : 0,
  level7          : 0,
  level8          : 0,
  level9          : 0,
  level0Bonus     : 0,
  level1Bonus     : 0,
  level2Bonus     : 0,
  level3Bonus     : 0,
  level4Bonus     : 0,
  level5Bonus     : 0,
  level6Bonus     : 0,
  level7Bonus     : 0,
  level8Bonus     : 0,
  level9Bonus     : 0,
  level0Fail      : 99,
  level1Fail      : 99,
  level2Fail      : 99,
  level3Fail      : 99,
  level4Fail      : 99,
  level5Fail      : 99,
  level6Fail      : 99,
  level7Fail      : 99,
  level8Fail      : 99,
  level9Fail      : 99,
  level0FailBonus : 0,
  level1FailBonus : 0,
  level2FailBonus : 0,
  level3FailBonus : 0,
  level4FailBonus : 0,
  level5FailBonus : 0,
  level6FailBonus : 0,
  level7FailBonus : 0,
  level8FailBonus : 0,
  level9FailBonus : 0,
  notes           : '',
  backstory       : '',
  spells          : [],
  skills          : [],
  feats           : [],
}