export const initValues = {
  firstNameValue     : '',
  middleNameValue    : '',
  lastNameValue      : '',
  titleValue         : '',
  characterTypeValue : 'PC',
  raceValue          : '',
  sexValue           : '',
  heightMValue       : 0,
  heightCmValue      : 0,
  weightValue        : 0,
  birthdayValue      : '',
  ageValue           : 18,
  descriptionValue   : '',
  hpValue            : 0,
  strValue           : 0,
  intValue           : 0,
  wisValue           : 0,
  conValue           : 0,
  dexValue           : 0,
  chaValue           : 0,
  backstoryValue     : '',
}

export const testValues = {
  firstNameValue     : 'Erik',
  middleNameValue    : 'Oliver',
  lastNameValue      : 'Christianson',
  titleValue         : 'Sir',
  characterTypeValue : 'PC',
  raceValue          : 'Human',
  sexValue           : 'Male',
  heightMValue       : 2,
  heightCmValue      : 0,
  weightValue        : 80,
  birthdayValue      : '12/10/1983',
  ageValue           : 18,
  descriptionValue   : 'Erik is tall with long blonde hair.',
  hpValue            : 20,
  strValue           : 16,
  intValue           : 14,
  wisValue           : 16,
  conValue           : 12,
  dexValue           : 12,
  chaValue           : 14,
  backstoryValue     : 'Erik is a philosopher',
}

export const initDirty = {
  firstNameDirty     : false,
  middleNameDirty    : false,
  lastNameDirty      : false,
  titleDirty         : false,
  characterTypeDirty : false,
  raceDirty          : false,
  sexDirty           : false,
  heightMDirty       : false,
  heightCmDirty      : false,
  weightDirty        : false,
  birthdayDirty      : false,
  ageDirty           : false,
  descriptionDirty   : false,
  hpDirty            : false,
  strDirty           : false,
  intDirty           : false,
  wisDirty           : false,
  conDirty           : false,
  dexDirty           : false,
  chaDirty           : false,
  backstoryDirty     : false,
};

export const initErrors = {
  firstNameRequired     : false,
  characterTypeRequired : false,
  heightMRequired       : false,
  heightCmRequired      : false,
  weightRequired        : false,
  hpRequired            : false,
  strRequired           : false,
  intRequired           : false,
  wisRequired           : false,
  conRequired           : false,
  dexRequired           : false,
  chaRequired           : false,
};
